-- Use in Localhost
CREATE DATABASE IF NOT EXISTS dbMakingPlans
 DEFAULT CHARACTER SET utf8 
 DEFAULT COLLATE utf8_general_ci;
 
 -- Use on the Server
CREATE DATABASE IF NOT EXISTS heroku_a566d595b7f40a7
 DEFAULT CHARACTER SET utf8 
 DEFAULT COLLATE utf8_general_ci;
